### ISSUE TITLE
Incorrect generated URL for S3 asset

### ISSUE THREAD

**Issue by j-greig** [onedesign/oneimgix#5]
For some reason the {{ url }} variable is resulting in a path that includes the full S3 path, rather than the correct Imgix path.

eg `https://cg.imgix.net/http%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Fgraphicalhouse-collective%2F998627ed-f099-4ab2-a853-d3b17641ebd8.png`

instead of `https://cg.imgix.net/998627ed-f099-4ab2-a853-d3b17641ebd8.png`

What could I be doing wrong? (I'm using Craft v 2.6.3003)

Thanks :)

**Comment by j-greig** [comment]
Was missing a trailing slash for the S3 bucket in settings 😬

**Comment by brianjhanson** [comment]
Hey @j-greig! Glad you got it sorted out, I was going to guess it was something like that, our find and replace scripts is pretty strict.

Thanks for using the plugin! Let us know if you run into any other issues with it.
